{% set name = "poppler-data" %}
{% set version = "0.4.11" %}
{% set sha256 = "2cec05cd1bb03af98a8b06a1e22f6e6e1a65b1e2f3816cb3069bb0874825f08c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script:
    - make install prefix=$PREFIX

requirements:
  build:
  run:

test:
  commands:
    - test -f $PREFIX/share/poppler/cidToUnicode/Adobe-CNS1

about:
  home: https://poppler.freedesktop.org/
  license: Adobe+GPLv2
  license_family: GPL
  license_file: COPYING
  summary: Encoding data for the Poppler PDF manipulation library.

extra:
  recipe-maintainers:
    - pkgw
