travis:
  secure:
    BINSTAR_TOKEN: m6LyyYYZmaGwG8PK07klW9R0u/nnQxIyJlfHJd6riLWtr2iuYsFCbjWL6tQRf/frJYKOQn77kX7l3mNQ+7sOarCCtqhIQYKSVEw94mlJr7SPomALfhLMULsvsLt+T/NhdcFXsEe5f8ATuSY8tJ3LjuymHpBeKtLixkT9lUFUEqGUQ7KV4hGHy4FqeI2fMQ1ust5fm1oikLOet50yyXL8XCkLhIUnmFryJBPWryDEbQ6Bqb2PPyfb8ymyz83PtNIf8Bxehpl6ycIC2ggdHkK84LeNRS6mDF45DTdVw/sK4dRm0zU6Q9j5O48TotGvbweon2aE7HcmPgWuHasFmqXihaWaMPeyPXwZrwUVMX1p+sqXneNdEyeZFtot0roQSyya4pa38hAIY5yXatKyq0BPWR8d7qUzPnHCYcgAwZw4BInaWfuQo36uaOS+DP9gFdUPw2jQ4uk7Op3QS1JtGSLaa0NSbmBOd2y5uPGFBFSl5XKFs5uTAguQ0zZD41JAX4vdnweFsu/0B0Dv06aMnjwYIWKhQ043dN5uGCDDIZy1TdJPJrlabuT5UaBFhlaHjupO/9z8NYtCyX98efNluAzNtoakkUM1umzL+w5v+uXk2P3TZYvF33agTvkyjpnuyy7VbYX0S9bSAHokRKY5ruKgUSIHk6pHt7Tel+1POHbl7UY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
